#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.ConfigMgr
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/ConfigMgr/List.cshtml")]
    public partial class List : System.Web.Mvc.WebViewPage<IList<Piranha.Manager.Config.ConfigBlock>>
    {
        public List()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
  
	ViewBag.Title = @Piranha.Manager.Resources.Config.ListTitle;

	var sections = Model.Where(b => b.Section.ToLower() != "general" && b.Section.ToLower() != "blogging").Select(b => b.Section).Distinct();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\tko.applyBindings(new manager.models.config());\r\n\t</script>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t<ul");

WriteLiteral(" class=\"nav nav-pills\"");

WriteLiteral(">\r\n\t\t\t<li");

WriteLiteral(" data-bind=\"css: { active: active() == \'general\' }\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"click: function() { setActive(\'general\'); }\"");

WriteLiteral(">");

            
            #line 16 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                                  Write(Piranha.Manager.Resources.Config.General);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n\t\t\t<li");

WriteLiteral(" data-bind=\"css: { active: active() == \'blogging\' }\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"click: function() { setActive(\'blogging\'); }\"");

WriteLiteral(">");

            
            #line 17 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                                    Write(Piranha.Manager.Resources.Config.Blogging);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 18 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
			
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
             foreach (var section in sections) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<li");

WriteLiteral(" data-bind=\"css: { active: active() == \'");

            
            #line 19 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                       Write(section.ToLower());

            
            #line default
            #line hidden
WriteLiteral("\' }\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-bind=\"click: function() { setActive(\'");

            
            #line 19 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                                      Write(section.ToLower());

            
            #line default
            #line hidden
WriteLiteral("\'); }\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                                                                 Write(section);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 20 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</ul>\r\n\t\t<br />\r\n\t</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t<form");

WriteLiteral(" role=\"form\"");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n\t\t\t<!-- General settings -->\r\n\t\t\t<div");

WriteLiteral(" data-bind=\"if: active() == \'general\'\"");

WriteLiteral(">\r\n\t\t\t\t<!-- Site -->\r\n\t\t\t\t<div");

WriteLiteral(" id=\"pnlSite\"");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<!-- Save -->\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-labeled btn-success\"");

WriteLiteral(" data-bind=\"click: saveSite\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

            
            #line 42 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                           Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">");

            
            #line 45 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                           Write(Piranha.Manager.Resources.Config.Site);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 50 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.SiteTitle);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: siteTitle\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 54 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.SiteTagline);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: siteTagline\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 60 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.SiteDescription);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<textarea");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" class=\"form-control count-me\"");

WriteLiteral(" style=\"height:97px\"");

WriteLiteral(" data-bind=\"value: siteDescription\"");

WriteLiteral("></textarea>\r\n\t\t\t\t\t\t\t\t\t<p><span");

WriteLiteral(" data-bind=\"text: siteDescription().Length\"");

WriteLiteral("></span>/255 ");

            
            #line 63 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                               Write(Piranha.Manager.Resources.Global.Characters);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t" +
"\t<!-- Permalinks -->\r\n\t\t\t\t<div");

WriteLiteral(" id=\"pnlPermalinks\"");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<!-- Save -->\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-labeled btn-success\"");

WriteLiteral(" data-bind=\"click: savePermalinks\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

            
            #line 82 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                           Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">");

            
            #line 85 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                           Write(Piranha.Manager.Resources.Config.Permalinks);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 90 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.PermalinksPageSlug);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: permalinkPage\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 94 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.PermalinksPostArchiveSlug);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: permalinkPostArchive\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 98 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.PermalinksTagArchiveSlug);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: permalinkTagArchive\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 104 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.PermalinksPostSlug);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: permalinkPost\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 108 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.PermalinksCategoryArchiveSlug);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: permalinkCategoryArchive\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t\t" +
"<!-- Cache -->\r\n\t\t\t\t<div");

WriteLiteral(" id=\"pnlCache\"");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<!-- Save -->\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-labeled btn-success\"");

WriteLiteral(" data-bind=\"click: saveCache\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

            
            #line 129 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                           Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">");

            
            #line 132 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                           Write(Piranha.Manager.Resources.Config.Cache);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 137 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.CacheExpires);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: cacheExpires\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 143 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.CacheMaxAge);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: cacheMaxAge\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t\t" +
"<!-- Params -->\r\n");

            
            #line 153 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
				
            
            #line default
            #line hidden
            
            #line 153 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                 foreach (var block in Model.Where(b => b.Section.ToLower() == "general")) {
					
            
            #line default
            #line hidden
            
            #line 154 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
               Write(Html.EditorFor(m => block));

            
            #line default
            #line hidden
            
            #line 154 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                               
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n\r\n\t\t\t<!-- Blog settings -->\r\n\t\t\t<div");

WriteLiteral(" data-bind=\"if: active() == \'blogging\'\"");

WriteLiteral(">\r\n\t\t\t\t<!-- Archive -->\r\n\t\t\t\t<div");

WriteLiteral(" id=\"pnlArchive\"");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<!-- Save -->\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-labeled btn-success\"");

WriteLiteral(" data-bind=\"click: saveArchive\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

            
            #line 172 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                           Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">");

            
            #line 175 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                           Write(Piranha.Manager.Resources.Config.Archive);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t\t<label>");

            
            #line 182 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                          Write(Piranha.Manager.Resources.Config.SiteArchiveTitle);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: siteArchiveTitle\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t\t<label>");

            
            #line 188 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                          Write(Piranha.Manager.Resources.Config.SiteArchivePageSize);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: siteArchivePageSize\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 194 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.SiteArchiveKeywords);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: siteArchiveKeywords\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 200 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.SiteArchiveDescription);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<textarea");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" class=\"form-control count-me\"");

WriteLiteral(" style=\"height:97px\"");

WriteLiteral(" data-bind=\"value: siteArchiveDescription\"");

WriteLiteral("></textarea>\r\n\t\t\t\t\t\t\t\t\t<p><span");

WriteLiteral(" data-bind=\"text: siteArchiveDescription().Length\"");

WriteLiteral("></span>/255 ");

            
            #line 203 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                      Write(Piranha.Manager.Resources.Global.Characters);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t" +
"\t<!-- Comments -->\r\n\t\t\t\t<div");

WriteLiteral(" id=\"pnlComments\"");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<!-- Save -->\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-labeled btn-success\"");

WriteLiteral(" data-bind=\"click: saveComments\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t</span>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

            
            #line 222 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                           Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">");

            
            #line 225 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                           Write(Piranha.Manager.Resources.Config.Comments);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<label>");

            
            #line 230 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                  Write(Piranha.Manager.Resources.Config.Moderators);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: commentModerators\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<label>\r\n\t\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: commentModerateAnonymous\"");

WriteLiteral(" /> <strong>");

            
            #line 238 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                   Write(Piranha.Manager.Resources.Config.ModerateAnonymous);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<label>\r\n\t\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: commentNotifyAuthor\"");

WriteLiteral(" /> <strong>");

            
            #line 243 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                              Write(Piranha.Manager.Resources.Config.NotifyAuthors);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<label>\r\n\t\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: commentModerateAuthorized\"");

WriteLiteral(" /> <strong>");

            
            #line 250 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                    Write(Piranha.Manager.Resources.Config.ModerateAuthorized);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<label>\r\n\t\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: commentNotifyModerators\"");

WriteLiteral(" /> <strong>");

            
            #line 255 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                                                                                  Write(Piranha.Manager.Resources.Config.NotifyModerators);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t<" +
"/div>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t\t<!-- Params -->\r\n");

            
            #line 264 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
				
            
            #line default
            #line hidden
            
            #line 264 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                 foreach (var block in Model.Where(b => b.Section.ToLower() == "blogging")) {
					
            
            #line default
            #line hidden
            
            #line 265 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
               Write(Html.EditorFor(m => block));

            
            #line default
            #line hidden
            
            #line 265 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                               
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n\r\n\t\t\t<!-- Custom sections -->\r\n");

            
            #line 270 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
			
            
            #line default
            #line hidden
            
            #line 270 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
             foreach (var section in sections) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<div");

WriteLiteral(" data-bind=\"if: active() == \'");

            
            #line 271 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                             Write(section.ToLower());

            
            #line default
            #line hidden
WriteLiteral("\'\"");

WriteLiteral(">\r\n\t\t\t\t\t<!-- Blocks -->\r\n");

            
            #line 273 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
					
            
            #line default
            #line hidden
            
            #line 273 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                     foreach (var block in Model.Where(b => b.Section.ToLower() == section.ToLower())) {
						
            
            #line default
            #line hidden
            
            #line 274 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                   Write(Html.EditorFor(m => block));

            
            #line default
            #line hidden
            
            #line 274 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
                                                   
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</div>\r\n");

            
            #line 277 "..\..\Areas\Manager\Views\ConfigMgr\List.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</form>\r\n\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
