#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.AccountMgr
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/AccountMgr/Login.cshtml")]
    public partial class Login : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Login()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
  
	Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n\t<meta");

WriteLiteral(" http-equiv=\"content-type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\"");

WriteLiteral(">\r\n\r\n\t<title>");

            
            #line 11 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
      Write(Piranha.Manager.Resources.Account.Login);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 291), Tuple.Create("\"", 332)
, Tuple.Create(Tuple.Create("", 298), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/img/icon.ico")
, 298), false)
);

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 373), Tuple.Create("\"", 414)
, Tuple.Create(Tuple.Create("", 380), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/img/icon.ico")
, 380), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 464), Tuple.Create("\"", 510)
, Tuple.Create(Tuple.Create("", 471), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/css/style.min.css")
, 471), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n\t<link");

WriteLiteral(" href=\"//fonts.googleapis.com/css?family=Open+Sans:300,400,600\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n</head>\r\n<body");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
		
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
         using (Html.BeginForm("LoginUser", "AccountMgr", FormMethod.Post, new { @role = "form", @class = "form" })) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"panel panel-white\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 22 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"account-logo\"");

WriteLiteral("></div>\r\n\t\t\t\t\t<p");

WriteLiteral(" class=\"account-banner\"");

WriteLiteral(">\r\n\t\t\t\t\t\tPiranha CMS\r\n\t\t\t\t\t\t<small>Version ");

            
            #line 27 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
                                  Write(Piranha.Utils.GetAssemblyVersion());

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n\t\t\t\t\t</p>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 30 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
                   Write(Html.TextBox("Username", "", new { @class = "form-control", @placeholder = @Piranha.Manager.Resources.Account.UsernamePlaceholder }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 33 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
                   Write(Html.Password("Password", "", new { @class = "form-control", @placeholder = @Piranha.Manager.Resources.Account.PasswordPlaceholder }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></span></button>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n");

            
            #line 38 "..\..\Areas\Manager\Views\AccountMgr\Login.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\t// Set focus to the first input field\r\n\t\tdocument.getElementById(\'Username\')" +
".focus();\r\n\t</script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
