#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n\t<meta");

WriteLiteral(" http-equiv=\"content-type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\"");

WriteLiteral(">\r\n\r\n\t<title>");

            
            #line 7 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 239), Tuple.Create("\"", 285)
, Tuple.Create(Tuple.Create("", 246), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/css/style.min.css")
, 246), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\t<link");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" rel=\"icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 361), Tuple.Create("\"", 402)
, Tuple.Create(Tuple.Create("", 368), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/img/icon.ico")
, 368), false)
);

WriteLiteral(">\r\n\t<link");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" rel=\"shortcut icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 452), Tuple.Create("\"", 493)
, Tuple.Create(Tuple.Create("", 459), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/img/icon.ico")
, 459), false)
);

WriteLiteral(">\r\n\r\n");

WriteLiteral("\t");

            
            #line 13 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("head", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");

            
            #line 15 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
  Write(ViewBag.IsSaved == true ? "class=pre-saved" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t<nav");

WriteLiteral(" class=\"navmenu navmenu-inverse navmenu-fixed-left\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n\t\t<a");

WriteLiteral(" class=\"navmenu-brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n\t\t\t<img");

WriteAttribute("src", Tuple.Create(" src=\"", 732), Tuple.Create("\"", 788)
            
            #line 18 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 738), Tuple.Create<System.Object, System.Int32>(Url.Content("~/manager/assets.ashx/img/logo.png")
            
            #line default
            #line hidden
, 738), false)
);

WriteLiteral(" />\r\n\t\t</a>\r\n");

WriteLiteral("\t\t");

            
            #line 20 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
   Write(Html.Partial("Partial/Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</nav>\r\n\r\n\t<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t\t\t<h1>");

            
            #line 26 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
               Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 27 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
				
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                 if (!String.IsNullOrWhiteSpace(ViewBag.SubTitle)) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<p");

WriteLiteral(" class=\"subtitle\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                   Write(ViewBag.SubTitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 29 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n\t\t</div>\r\n\r\n");

WriteLiteral("\t\t");

            
            #line 33 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\r\n\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t</div>\r\n\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\tvar baseUrl = \'");

            
            #line 41 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                  Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\t</script>\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1355), Tuple.Create("\"", 1400)
, Tuple.Create(Tuple.Create("", 1361), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/js/scripts.min.js")
, 1361), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("\t");

            
            #line 44 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("script", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
