#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n\t<meta");

WriteLiteral(" http-equiv=\"content-type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\"");

WriteLiteral(">\r\n\r\n\t<title>");

            
            #line 7 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 239), Tuple.Create("\"", 280)
, Tuple.Create(Tuple.Create("", 246), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/img/icon.ico")
, 246), false)
);

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 321), Tuple.Create("\"", 362)
, Tuple.Create(Tuple.Create("", 328), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/img/icon.ico")
, 328), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 412), Tuple.Create("\"", 458)
, Tuple.Create(Tuple.Create("", 419), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/css/style.min.css")
, 419), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\t<link");

WriteLiteral(" href=\"//fonts.googleapis.com/css?family=Open+Sans:300,400,600\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n\r\n");

            
            #line 14 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
	
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
     if (!String.IsNullOrEmpty(ViewBag.Message)) {

            
            #line default
            #line hidden
WriteLiteral("\t\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\t\tsetTimeout(function () {\r\n\t\t\t\t$(\".sys-message\").slideUp();\r\n\t\t\t}, 2000);\r\n\t" +
"\t</script>\r\n");

            
            #line 20 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("\t");

            
            #line 21 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("head", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");

            
            #line 23 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
  Write(ViewBag.IsSaved == true ? "class=pre-saved" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t<nav");

WriteLiteral(" class=\"navmenu navmenu-inverse navmenu-fixed-left\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n\t\t<a");

WriteLiteral(" class=\"navmenu-brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n\t\t\t<img");

WriteAttribute("src", Tuple.Create(" src=\"", 1015), Tuple.Create("\"", 1076)
            
            #line 26 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1021), Tuple.Create<System.Object, System.Int32>(Url.Content("~/manager/assets.ashx/img/logo-menu.png")
            
            #line default
            #line hidden
, 1021), false)
);

WriteLiteral(" />\r\n\t\t</a>\r\n\r\n");

WriteLiteral("\t\t");

            
            #line 29 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
   Write(Html.Partial("Partial/Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</nav>\r\n\r\n\t<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n\t\t\t<h1>");

            
            #line 34 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 35 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
			
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
             if (!String.IsNullOrWhiteSpace(ViewBag.SubTitle)) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<p");

WriteLiteral(" class=\"subtitle\"");

WriteLiteral(">");

            
            #line 36 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                               Write(ViewBag.SubTitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 37 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</div>\r\n\t</div>\r\n\t<div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 41 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\r\n\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t</div>\r\n\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\tvar baseUrl = \'");

            
            #line 49 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                  Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\t</script>\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1632), Tuple.Create("\"", 1677)
, Tuple.Create(Tuple.Create("", 1638), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/js/scripts.min.js")
, 1638), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("\t");

            
            #line 52 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("script", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
