#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/Partial/Editor.cshtml")]
    public partial class Editor : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Editor()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
  
	var height = ViewData.Eval("height") != null ? (int)ViewData.Eval("height") : 340;
	var autoresize = ViewData.Eval("autoresize") != null ? (bool)ViewData.Eval("autoresize") : true;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 221), Tuple.Create("\"", 279)
, Tuple.Create(Tuple.Create("", 227), Tuple.Create<System.Object, System.Int32>(Href("~/manager/assets.ashx/vendor/tiny_mce/tinymce.min.js")
, 227), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\ttinymce.init({\r\n\t\tmode: \'specific_textareas\',\r\n\t\teditor_selector: \"editor\",\r\n" +
"\t\tconvert_urls: false,\r\n\t\tplugins: [\r\n\t\t\"");

            
            #line 12 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
     Write(autoresize ? "autoresize" : "");

            
            #line default
            #line hidden
WriteLiteral(" autolink code hr paste link\"\r\n\t\t],\r\n\t\twidth: \"100%\",\r\n\t\theight: \"");

            
            #line 15 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
            Write(height);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n");

            
            #line 16 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
		
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
         if (autoresize) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("autoresize_min_height: 340,");

WriteLiteral("\r\n");

            
            #line 18 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t\tmenubar: false,\r\n\t\tstatusbar: false,\r\n\t\tcontent_css: \"");

            
            #line 21 "..\..\Areas\Manager\Views\Shared\Partial\Editor.cshtml"
                 Write(Url.Content("~/manager/assets.ashx/css/editor.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n\t\ttoolbar: \"bold italic underline | bullist numlist hr | formatselect removef" +
"ormat | cut copy paste | link | code\",\r\n\t});\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
