#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    #line 1 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
    using Piranha.Manager;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/Partial/Menu.cshtml")]
    public partial class Menu : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Menu()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
  
	var controller = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString().ToLower();

            
            #line default
            #line hidden
WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"nav navmenu-nav\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
	
            
            #line default
            #line hidden
            
            #line 6 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
     foreach (var group in Piranha.Manager.Menu.Items) {
		if (group.Items.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<li>\r\n\t\t\t\t<span ");

            
            #line 9 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
                  Write(!String.IsNullOrWhiteSpace(group.Css) ? "class=" + group.Css : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 9 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
                                                                                      Write(group.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t\t<ul>\r\n");

            
            #line 11 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
					
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
                     foreach (var item in group.Items) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<li ");

            
            #line 12 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
                        Write(item.Controller.ToLower() == controller ? "class=active" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t\t\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 510), Tuple.Create("\"", 558)
            
            #line 13 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
, Tuple.Create(Tuple.Create("", 517), Tuple.Create<System.Object, System.Int32>(Url.Action(item.Action, item.Controller)
            
            #line default
            #line hidden
, 517), false)
);

WriteLiteral(">");

            
            #line 13 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
                                                                           Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t\t\t</li>\r\n");

            
            #line 15 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</ul>\r\n\t\t\t</li>\r\n");

            
            #line 18 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
		}
	}

            
            #line default
            #line hidden
WriteLiteral("\t<li>\r\n\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 638), Tuple.Create("\"", 684)
            
            #line 21 "..\..\Areas\Manager\Views\Shared\Partial\Menu.cshtml"
, Tuple.Create(Tuple.Create("", 645), Tuple.Create<System.Object, System.Int32>(Url.Action("LogoutUser", "AccountMgr")
            
            #line default
            #line hidden
, 645), false)
);

WriteLiteral(" class=\"ico-logout\"");

WriteLiteral(">Logout</a>\r\n\t</li>\r\n</ul>\r\n");

        }
    }
}
#pragma warning restore 1591
