#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.BlockMgr.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/BlockMgr/Partial/EditBlock.cshtml")]
    public partial class EditBlock : System.Web.Mvc.WebViewPage<dynamic>
    {
        public EditBlock()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
  
	Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"panel panel-primary panel-add\"");

WriteLiteral(" >\r\n\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" id=\"addBlockTitle\"");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">\r\n\t\t\t\t\t<span");

WriteLiteral(" class=\"glyphicon glyphicon-plus pull-right\"");

WriteLiteral("></span>\r\n\t\t\t\t\t<a");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" href=\"#addBlock\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"addBlock\"");

WriteLiteral(" data-bind=\"text: title\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 15 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
                   Write(Piranha.Manager.Resources.Block.AddTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</a>\r\n\t\t\t\t</h3>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" id=\"addBlock\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" aria-labelledby=\"addBlockTitle\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t<form");

WriteLiteral(" role=\"form\"");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"css: { \'has-error has-feedback\': nameValid() != true }\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 965), Tuple.Create("\"", 1027)
            
            #line 25 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
          , Tuple.Create(Tuple.Create("", 979), Tuple.Create<System.Object, System.Int32>(Piranha.Manager.Resources.Block.NamePlaceholder
            
            #line default
            #line hidden
, 979), false)
);

WriteLiteral(" data-bind=\"value: name\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t\t<!-- ko if: !nameValid() -->\r\n\t\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"glyphicon glyphicon-remove form-control-feedback\"");

WriteLiteral("></span>\r\n\t\t\t\t\t\t\t\t\t<!-- /ko -->\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1344), Tuple.Create("\"", 1406)
            
            #line 33 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
         , Tuple.Create(Tuple.Create("", 1358), Tuple.Create<System.Object, System.Int32>(Piranha.Manager.Resources.Block.SlugPlaceholder
            
            #line default
            #line hidden
, 1358), false)
);

WriteLiteral(" data-bind=\"value: slug\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"css: { \'has-error has-feedback\': descriptionValid() != true }\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<textarea");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" class=\"form-control meta\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1703), Tuple.Create("\"", 1772)
            
            #line 40 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
                  , Tuple.Create(Tuple.Create("", 1717), Tuple.Create<System.Object, System.Int32>(Piranha.Manager.Resources.Block.DescriptionPlaceholder
            
            #line default
            #line hidden
, 1717), false)
);

WriteLiteral(" data-bind=\"value: description\"");

WriteLiteral("></textarea>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<textarea");

WriteLiteral(" class=\"form-control editor\"");

WriteLiteral(" data-bind=\"text: body\"");

WriteLiteral("></textarea>\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</form>\r\n\t\t\t\t</di" +
"v>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n\t\t\t\t\t<button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" data-bind=\"click: save\"");

WriteLiteral(">");

            
            #line 54 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
                                                                       Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t\t<button");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" data-bind=\"click: clear\"");

WriteLiteral(">");

            
            #line 55 "..\..\Areas\Manager\Views\BlockMgr\Partial\EditBlock.cshtml"
                                                                       Write(Piranha.Manager.Resources.Global.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
