#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.AliasMgr.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/AliasMgr/Partial/EditAlias.cshtml")]
    public partial class EditAlias : System.Web.Mvc.WebViewPage<dynamic>
    {
        public EditAlias()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
  
	Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"panel panel-primary panel-add\"");

WriteLiteral(" >\r\n\t\t\t<div");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"icon\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok-circle\"");

WriteLiteral("></span></div>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" id=\"addAliasTitle\"");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">\r\n\t\t\t\t\t<span");

WriteLiteral(" class=\"glyphicon glyphicon-plus pull-right\"");

WriteLiteral("></span>\r\n\t\t\t\t\t<a");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" href=\"#addAlias\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"addAlias\"");

WriteLiteral(" data-bind=\"text: title\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 15 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
                   Write(Piranha.Manager.Resources.Alias.AddTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</a>\r\n\t\t\t\t</h3>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" id=\"addAlias\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" aria-labelledby=\"addAliasTitle\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t\t<form");

WriteLiteral(" role=\"form\"");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"css: { \'has-error has-feedback\': oldUrlValid() != true }\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 967), Tuple.Create("\"", 1031)
            
            #line 25 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
          , Tuple.Create(Tuple.Create("", 981), Tuple.Create<System.Object, System.Int32>(Piranha.Manager.Resources.Alias.OldUrlPlaceholder
            
            #line default
            #line hidden
, 981), false)
);

WriteLiteral(" data-bind=\"value: oldUrl\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t\t<!-- ko if: !oldUrlValid() -->\r\n\t\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"glyphicon glyphicon-remove form-control-feedback\"");

WriteLiteral("></span>\r\n\t\t\t\t\t\t\t\t\t<!-- /ko -->\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" data-bind=\"css: { \'has-error has-feedback\': newUrlValid() != true }\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1421), Tuple.Create("\"", 1485)
            
            #line 33 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
         , Tuple.Create(Tuple.Create("", 1435), Tuple.Create<System.Object, System.Int32>(Piranha.Manager.Resources.Alias.NewUrlPlaceholder
            
            #line default
            #line hidden
, 1435), false)
);

WriteLiteral(" data-bind=\"value: newUrl\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t\t<!-- ko if: !newUrlValid() -->\r\n\t\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"glyphicon glyphicon-remove form-control-feedback\"");

WriteLiteral("></span>\r\n\t\t\t\t\t\t\t\t\t<!-- /ko -->\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t" +
"\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" data-bind=\"checked: isPermanent\"");

WriteLiteral(" />\r\n\t\t\t\t\t\t\t\t<label");

WriteLiteral(" class=\"label-small label-up\"");

WriteLiteral(">");

            
            #line 43 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
                                                               Write(Piranha.Manager.Resources.Alias.IsPermanent);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</form>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n\t\t\t\t\t<button");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" data-bind=\"click: save\"");

WriteLiteral(">");

            
            #line 49 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
                                                                       Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t\t<button");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" data-bind=\"click: clear\"");

WriteLiteral(">");

            
            #line 50 "..\..\Areas\Manager\Views\AliasMgr\Partial\EditAlias.cshtml"
                                                                       Write(Piranha.Manager.Resources.Global.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
