#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.PostMgr
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/PostMgr/List.cshtml")]
    public partial class List : System.Web.Mvc.WebViewPage<Piranha.Manager.Models.Post.ListModel>
    {
        public List()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
  
	ViewBag.Title = Piranha.Manager.Resources.Post.ListTitle;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\tvar options = {\r\n\t\t\tvalueNames: [\'post-title\', \'post-type\', \'post-updated\', " +
"\'post-created\']\r\n\t\t};\r\n\t\tvar postList = new List(\'post-list\', options);\r\n\t</scri" +
"pt>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
             if (Model.PostTypes.Count > 1 && Model.IsDefaultSelection) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<div");

WriteLiteral(" class=\"btn-group pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-labeled btn-primary\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t</span>");

            
            #line 22 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                          Write(Piranha.Manager.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</button>\r\n\t\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n\t\t\t\t\t\t<span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle Dropdown</span>\r\n\t\t\t\t\t</button>\r\n\t\t\t\t\t<ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
						
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                         foreach (var type in Model.PostTypes) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1076), Tuple.Create("\"", 1128)
            
            #line 30 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
, Tuple.Create(Tuple.Create("", 1083), Tuple.Create<System.Object, System.Int32>(Url.Action("Add", new { @type = type.Slug })
            
            #line default
            #line hidden
, 1083), false)
);

WriteLiteral(">");

            
            #line 30 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                                                   Write(type.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 31 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
						}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t</ul>\r\n\t\t\t\t</div>\r\n");

            
            #line 34 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			} else {
				var type = Model.IsDefaultSelection ? Model.PostTypes.FirstOrDefault() : Model.PostTypes.Where(t => t.IsActive).Single();


            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<div");

WriteLiteral(" class=\"btn-group submit pull-right\"");

WriteLiteral(">\r\n\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1380), Tuple.Create("\"", 1432)
            
            #line 38 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
, Tuple.Create(Tuple.Create("", 1387), Tuple.Create<System.Object, System.Int32>(Url.Action("Add", new { @type = type.Slug })
            
            #line default
            #line hidden
, 1387), false)
);

WriteLiteral(" class=\"btn btn-primary btn-labeled\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t</span>");

            
            #line 41 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                          Write(Piranha.Manager.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</a>\r\n\t\t\t\t</div>\r\n");

            
            #line 44 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t<!-- Post type filter -->\r\n");

            
            #line 47 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
             if (Model.PostTypes.Count > 1) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<ul");

WriteLiteral(" class=\"nav nav-pills\"");

WriteLiteral(">\r\n\t\t\t\t\t<li ");

            
            #line 49 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                    Write(Model.IsDefaultSelection ? "class=active" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1805), Tuple.Create("\"", 1851)
            
            #line 50 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
, Tuple.Create(Tuple.Create("", 1812), Tuple.Create<System.Object, System.Int32>(Url.Action("List", new { @slug = "" })
            
            #line default
            #line hidden
, 1812), false)
);

WriteLiteral(">");

            
            #line 50 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                                     Write(Piranha.Manager.Resources.Global.All);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t\t</li>\r\n");

            
            #line 52 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
					
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                     foreach (var type in Model.PostTypes) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<li ");

            
            #line 53 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                        Write(type.IsActive ? "class=active" : "");

            
            #line default
            #line hidden
WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2006), Tuple.Create("\"", 2059)
            
            #line 53 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
, Tuple.Create(Tuple.Create("", 2013), Tuple.Create<System.Object, System.Int32>(Url.Action("List", new { @slug = type.Slug })
            
            #line default
            #line hidden
, 2013), false)
);

WriteLiteral(">");

            
            #line 53 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                                                                                       Write(type.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 54 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</ul>\r\n");

WriteLiteral("\t\t\t\t<br />\r\n");

            
            #line 57 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</div>\r\n\t</div>\r\n\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<!-- Actions -->\r\n\t\t<div");

WriteLiteral(" class=\"col-sm-12 buttons\"");

WriteLiteral(">\r\n\t\t</div>\r\n\t</div>\r\n\r\n\t<!-- Post table -->\r\n\t<table");

WriteLiteral(" id=\"post-list\"");

WriteLiteral(" class=\"table table-striped table-main\"");

WriteLiteral(">\r\n\t\t<thead>\r\n\t\t\t<tr>\r\n\t\t\t\t<th><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"post-title\"");

WriteLiteral(">");

            
            #line 71 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                         Write(Piranha.Manager.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n\t\t\t\t<th><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"post-type\"");

WriteLiteral(">");

            
            #line 72 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                        Write(Piranha.Manager.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n\t\t\t\t<th");

WriteLiteral(" class=\"date\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"post-updated\"");

WriteLiteral(">");

            
            #line 73 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                                        Write(Piranha.Manager.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n\t\t\t\t<th");

WriteLiteral(" class=\"date\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"post-created\"");

WriteLiteral(">");

            
            #line 74 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                                        Write(Piranha.Manager.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n\t\t\t\t<th");

WriteLiteral(" class=\"actions one\"");

WriteLiteral("></th>\r\n\t\t\t</tr>\r\n\t\t</thead>\r\n\t\t<tbody");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			
            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
             foreach (var post in Model.Items) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<tr ");

            
            #line 80 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                Write(!post.Published.HasValue ? "class=unpublished" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<a");

WriteLiteral(" class=\"post-title\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3011), Tuple.Create("\"", 3059)
            
            #line 82 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
, Tuple.Create(Tuple.Create("", 3018), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { id = post.Id })
            
            #line default
            #line hidden
, 3018), false)
);

WriteLiteral(">");

            
            #line 82 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                                                                          Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t\t\t\t<p");

WriteLiteral(" class=\"meta\"");

WriteLiteral(">\r\n");

            
            #line 84 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
							
            
            #line default
            #line hidden
            
            #line 84 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                             if (post.Published.HasValue) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t");

WriteLiteral("Published: ");

            
            #line 85 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                            Write(post.Published.Value.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 86 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
							} else {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t");

WriteLiteral("Unpublished");

WriteLiteral("\r\n");

            
            #line 88 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
							}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t</p>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<td");

WriteLiteral(" class=\"post-type\"");

WriteLiteral(">");

            
            #line 91 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                     Write(post.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t<td");

WriteLiteral(" class=\"post-updated\"");

WriteLiteral(">");

            
            #line 92 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                        Write(post.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t<td");

WriteLiteral(" class=\"post-created\"");

WriteLiteral(">");

            
            #line 93 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
                                        Write(post.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t<td");

WriteLiteral(" class=\"actions\"");

WriteLiteral("><a");

WriteLiteral(" class=\"delete\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3537), Tuple.Create("\"", 3588)
            
            #line 94 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
, Tuple.Create(Tuple.Create("", 3544), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", new { @id = post.Id })
            
            #line default
            #line hidden
, 3544), false)
);

WriteLiteral("></a></td>\r\n\t\t\t\t</tr>\r\n");

            
            #line 96 "..\..\Areas\Manager\Views\PostMgr\List.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</tbody>\r\n\t</table>\r\n</div>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
