#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.PostMgr.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/PostMgr/Partial/CommentList.cshtml")]
    public partial class CommentList : System.Web.Mvc.WebViewPage<IList<Piranha.Manager.Models.Post.EditModel.CommentListItem>>
    {
        public CommentList()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Manager\Views\PostMgr\Partial\CommentList.cshtml"
  
	Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n\t<thead>\r\n\t\t<tr>\r\n\t\t\t<th");

WriteLiteral(" class=\"date\"");

WriteLiteral(">");

            
            #line 9 "..\..\Areas\Manager\Views\PostMgr\Partial\CommentList.cshtml"
                        Write(Piranha.Manager.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n\t\t\t<th>Author</th>\r\n\t\t\t<th");

WriteLiteral(" class=\"date\"");

WriteLiteral(">Approved</th>\r\n\t\t\t<th");

WriteLiteral(" class=\"date\"");

WriteLiteral(">Spam</th>\r\n\t\t</tr>\r\n\t</thead>\r\n\t<tbody>\r\n");

WriteLiteral("\t\t");

            
            #line 16 "..\..\Areas\Manager\Views\PostMgr\Partial\CommentList.cshtml"
   Write(Html.EditorFor(m => m));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</tbody>\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
