#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.PostTypeMgr
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/PostTypeMgr/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<Piranha.Manager.Models.PostType.EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
 using (var form = Html.BeginForm("Save", "PostTypeMgr", FormMethod.Post, new { @class = "form", @role = "form" })) {
	
            
            #line default
            #line hidden
            
            #line 4 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 4 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                            
	
            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                              


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"col-sm-12 buttons\"");

WriteLiteral(">\r\n\t\t\t\t<!-- Actions -->\r\n\t\t\t\t<div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n\t\t\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-labeled btn-success\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<span");

WriteLiteral(" class=\"btn-label\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t</span>");

            
            #line 15 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                          Write(Piranha.Manager.Resources.Global.Save);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</button>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 24 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control title", @placeholder = "Add name" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 25 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 32 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.TextAreaFor(m => m.Description, new { @class = "form-control count-me", @rows = 7, @placeholder = "Add optional description" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t<p><span>");

            
            #line 33 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                         Write(!String.IsNullOrEmpty(Model.Description) ? Model.Description.Length : 0);

            
            #line default
            #line hidden
WriteLiteral("</span>/255 characters</p>\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 34 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 39 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.LabelFor(m => m.Route, Piranha.Manager.Resources.Global.Route));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 40 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.TextBoxFor(m => m.Route, new { @class = "form-control meta", @placeholder = "Add optional route" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 41 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Route));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 44 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.LabelFor(m => m.View, Piranha.Manager.Resources.Global.View));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 45 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.TextBoxFor(m => m.View, new { @class = "form-control meta", @placeholder = "Add optional view" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 46 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.View));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 49 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.LabelFor(m => m.CommentRoute, Piranha.Manager.Resources.PostType.CommentRoute));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 50 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.TextBoxFor(m => m.CommentRoute, new { @class = "form-control meta", @placeholder = "Add optional comment route" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 51 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.CommentRoute));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\r\n\t\t<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n\t\t\t\t<span");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 59 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.LabelFor(m => m.EnableArchive, "Generate archive automatically", new { @class = "label-small" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 60 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
               Write(Html.CheckBoxFor(m => m.EnableArchive));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</span>\r\n\t\t\t\t<h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">Archive settings</h3>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t\t\t\t<!-- Post type settings -->\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 69 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.LabelFor(m => m.ArchiveTitle, Piranha.Manager.Resources.PostType.ArchiveTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 70 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.ArchiveTitle, new { @class = "form-control meta", @placeholder = "Add archive title" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 71 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.ArchiveTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 74 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Slug, Piranha.Manager.Resources.Global.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 75 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Slug, new { @class = "form-control meta", @placeholder = "A slug will be generated automatically" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 76 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 79 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.LabelFor(m => m.ArchiveRoute, Piranha.Manager.Resources.PostType.ArchiveRoute));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 80 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.ArchiveRoute, new { @class = "form-control meta", @placeholder = "Add optional archive route" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 81 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.ArchiveRoute));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 84 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.LabelFor(m => m.ArchiveView, Piranha.Manager.Resources.PostType.ArchiveView));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 85 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.ArchiveView, new { @class = "form-control meta", @placeholder = "Add optional archive view" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 86 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.ArchiveView));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t<!-- Archive settings -->\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 93 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.LabelFor(m => m.MetaKeywords, Piranha.Manager.Resources.Global.MetaKeywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 94 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.MetaKeywords, new { @class = "form-control meta", @placeholder = "Add archive meta keywords" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 95 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.MetaKeywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group with-label\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 98 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.LabelFor(m => m.MetaDescription, Piranha.Manager.Resources.Global.MetaDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 99 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.MetaDescription, new { @class = "form-control meta count-me", @rows = 7, @style = "height:164px", @placeholder = "Add archive meta description" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t<p><span>");

            
            #line 100 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                                 Write(!String.IsNullOrEmpty(Model.MetaDescription) ? Model.MetaDescription.Length : 0);

            
            #line default
            #line hidden
WriteLiteral("</span>/255 characters</p>\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 101 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.MetaDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n");

            
            #line 108 "..\..\Areas\Manager\Views\PostTypeMgr\Edit.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
